#include "Clip_Wrapper.h"
#include "Texture.h"

#include <SDL.h>

//Allocating memory for animation clips in bulk
ClipWrapper::ClipWrapper()
    :SPRITE_TOTAL(640), TILE_W(16), TILE_H(16)
{
    SPRITE_CLIPS = new SDL_Rect[SPRITE_TOTAL];

    PACMAN_CLIPS_RIGHT = new SDL_Rect[PACMAN_RIGHT_TOTAL];
    PACMAN_CLIPS_LEFT = new SDL_Rect[PACMAN_LEFT_TOTAL];
    PACMAN_CLIPS_UP = new SDL_Rect[PACMAN_UP_TOTAL];
    PACMAN_CLIPS_DOWN = new SDL_Rect[PACMAN_DOWN_TOTAL];
    PACMAN_CLIPS_DEATH = new SDL_Rect[PACMAN_DEATH_TOTAL];

    ENERGIZER_CLIPS = new SDL_Rect[PELLET_TOTAL];

    BLINKY_CLIPS_RIGHT = new SDL_Rect[GHOST_TOTAL];
    BLINKY_CLIPS_DOWN = new SDL_Rect[GHOST_TOTAL];
    BLINKY_CLIPS_LEFT = new SDL_Rect[GHOST_TOTAL];
    BLINKY_CLIPS_UP = new SDL_Rect[GHOST_TOTAL];

    PINKY_CLIPS_RIGHT = new SDL_Rect[GHOST_TOTAL];
    PINKY_CLIPS_DOWN = new SDL_Rect[GHOST_TOTAL];
    PINKY_CLIPS_LEFT = new SDL_Rect[GHOST_TOTAL];
    PINKY_CLIPS_UP = new SDL_Rect[GHOST_TOTAL];

    INKY_CLIPS_RIGHT = new SDL_Rect[GHOST_TOTAL];
    INKY_CLIPS_DOWN = new SDL_Rect[GHOST_TOTAL];
    INKY_CLIPS_LEFT = new SDL_Rect[GHOST_TOTAL];
    INKY_CLIPS_UP = new SDL_Rect[GHOST_TOTAL];

    CLYDE_CLIPS_RIGHT = new SDL_Rect[GHOST_TOTAL];
    CLYDE_CLIPS_DOWN = new SDL_Rect[GHOST_TOTAL];
    CLYDE_CLIPS_LEFT = new SDL_Rect[GHOST_TOTAL];
    CLYDE_CLIPS_UP = new SDL_Rect[GHOST_TOTAL];

    EYES_CLIPS_RIGHT = new SDL_Rect[GHOST_TOTAL];
    EYES_CLIPS_LEFT = new SDL_Rect[GHOST_TOTAL];
    EYES_CLIPS_UP = new SDL_Rect[GHOST_TOTAL];
    EYES_CLIPS_DOWN = new SDL_Rect[GHOST_TOTAL];

    FRIGHT_CLIPS = new SDL_Rect[GHOST_TOTAL];
    FRIGHT_END_CLIPS = new SDL_Rect[GHOST_TOTAL];

    LETTER_CLIPS = new SDL_Rect[LETTER_TOTAL];
    DIGIT_CLIPS = new SDL_Rect[DIGIT_TOTAL];
    SCORE_CLIPS = new SDL_Rect[SCORE_TOTAL];
    FRUIT_CLIPS = new SDL_Rect[ITEM_TOTAL];

    BIG_PACMAN_CLIPS = new SDL_Rect[PACMAN_RIGHT_TOTAL];
    TORN_BLINKY_CLIPS = new SDL_Rect[GHOST_TOTAL];
    PATCHED_BLINKY_CLIPS = new SDL_Rect[GHOST_TOTAL];
    BLINKY_CLOAK_TEAR_CLIPS = new SDL_Rect[CLOAK_TEAR_TOTAL];
    BLINKY_WITHOUT_CLOAK_CLIPS = new SDL_Rect[GHOST_TOTAL];
}


//Releasing memory in bulk
ClipWrapper::~ClipWrapper()
{
    delete[]SPRITE_CLIPS;
    SPRITE_CLIPS = nullptr;

    delete[]PACMAN_CLIPS_RIGHT;
    PACMAN_CLIPS_RIGHT = nullptr;

    delete[]PACMAN_CLIPS_LEFT;
    PACMAN_CLIPS_LEFT = nullptr;

    delete[]PACMAN_CLIPS_UP;
    PACMAN_CLIPS_UP = nullptr;

    delete[]PACMAN_CLIPS_DOWN;
    PACMAN_CLIPS_DOWN = nullptr;

    delete[]PACMAN_CLIPS_DEATH;
    PACMAN_CLIPS_DEATH = nullptr;

    delete[]ENERGIZER_CLIPS;
    ENERGIZER_CLIPS = nullptr;

    delete[]BLINKY_CLIPS_RIGHT;
    BLINKY_CLIPS_RIGHT = nullptr;

    delete[]BLINKY_CLIPS_DOWN;
    BLINKY_CLIPS_DOWN = nullptr;

    delete[]BLINKY_CLIPS_LEFT;
    BLINKY_CLIPS_LEFT = nullptr;

    delete[]BLINKY_CLIPS_UP;
    BLINKY_CLIPS_UP = nullptr;

    delete[]PINKY_CLIPS_RIGHT;
    PINKY_CLIPS_RIGHT = nullptr;

    delete[]PINKY_CLIPS_LEFT;
    PINKY_CLIPS_LEFT = nullptr;

    delete[]PINKY_CLIPS_UP;
    PINKY_CLIPS_UP = nullptr;

    delete[]PINKY_CLIPS_DOWN;
    PINKY_CLIPS_DOWN = nullptr;

    delete[]INKY_CLIPS_RIGHT;
    INKY_CLIPS_RIGHT = nullptr;

    delete[]INKY_CLIPS_LEFT;
    INKY_CLIPS_LEFT = nullptr;

    delete[]INKY_CLIPS_UP;
    INKY_CLIPS_UP = nullptr;

    delete[]INKY_CLIPS_DOWN;
    INKY_CLIPS_DOWN = nullptr;

    delete[]CLYDE_CLIPS_RIGHT;
    CLYDE_CLIPS_RIGHT = nullptr;

    delete[]CLYDE_CLIPS_LEFT;
    CLYDE_CLIPS_LEFT = nullptr;

    delete[]CLYDE_CLIPS_UP;
    CLYDE_CLIPS_UP = nullptr;

    delete[]CLYDE_CLIPS_DOWN;
    CLYDE_CLIPS_DOWN = nullptr;

    delete[]EYES_CLIPS_RIGHT;
    EYES_CLIPS_RIGHT = nullptr;

    delete[]EYES_CLIPS_LEFT;
    EYES_CLIPS_LEFT = nullptr;

    delete[]EYES_CLIPS_UP;
    EYES_CLIPS_UP = nullptr;

    delete[]EYES_CLIPS_DOWN;
    EYES_CLIPS_DOWN = nullptr;

    delete[]FRIGHT_CLIPS;
    FRIGHT_CLIPS = nullptr;

    delete[]FRIGHT_END_CLIPS;
    FRIGHT_END_CLIPS = nullptr;

    delete[]LETTER_CLIPS;
    LETTER_CLIPS = nullptr;

    delete[]DIGIT_CLIPS;
    DIGIT_CLIPS = nullptr;

    delete[]SCORE_CLIPS;
    SCORE_CLIPS = nullptr;

    delete[]FRUIT_CLIPS;
    FRUIT_CLIPS = nullptr;

    delete[]BIG_PACMAN_CLIPS;
    BIG_PACMAN_CLIPS = nullptr;

    delete[]TORN_BLINKY_CLIPS;
    TORN_BLINKY_CLIPS = nullptr;

    delete[]PATCHED_BLINKY_CLIPS;
    PATCHED_BLINKY_CLIPS = nullptr;

    delete[]BLINKY_CLOAK_TEAR_CLIPS;
    BLINKY_CLOAK_TEAR_CLIPS = nullptr;

    delete[]BLINKY_WITHOUT_CLOAK_CLIPS;
    BLINKY_WITHOUT_CLOAK_CLIPS = nullptr;
}


//Loading sprite sheet images to a clip container
//Then sorting those clips into animation categories using the clip container
void ClipWrapper::load(Texture& sprites)
{
    //If sprite sheet loaded successfully, assign clips from sheet to SPRITE_CLIPS buffer
    int x = 0;
    int y = 0;

    int size = (sprites.getWidth() / TILE_W) * (sprites.getHeight() / TILE_H);

    for (int i = 0; i < size; i++)
    {
        SPRITE_CLIPS[i].x = x;
        SPRITE_CLIPS[i].y = y;
        SPRITE_CLIPS[i].w = TILE_W;
        SPRITE_CLIPS[i].h = TILE_H;

        x += TILE_W;
        if (x >= sprites.getWidth())
        {
            x = 0;
            y += TILE_H;
        }
    }


    //Assign loaded clips from SPRITE_CLIPS buffer to separate animation cateories for clarity/simple access;
    //Default height/width per item - 16 px;
    //Entity height/width - 32 px.

    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_FULL].x = SPRITE_CLIPS[448].x;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_FULL].y = SPRITE_CLIPS[448].y;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_FULL].w = TILE_W * 2;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_FULL].h = TILE_H * 2;

    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN].x = SPRITE_CLIPS[204].x;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN].y = SPRITE_CLIPS[204].y;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN].w = TILE_W * 2;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN].h = TILE_H * 2;

    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_OPEN].x = SPRITE_CLIPS[200].x;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_OPEN].y = SPRITE_CLIPS[200].y;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_OPEN].w = TILE_W * 2;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_OPEN].h = TILE_H * 2;

    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN2].x = SPRITE_CLIPS[204].x;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN2].y = SPRITE_CLIPS[204].y;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN2].w = TILE_W * 2;
    PACMAN_CLIPS_RIGHT[PACMAN_RIGHT_HALFOPEN2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PACMAN_CLIPS_LEFT[PACMAN_LEFT_FULL].x = SPRITE_CLIPS[448].x;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_FULL].y = SPRITE_CLIPS[448].y;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_FULL].w = TILE_W * 2;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_FULL].h = TILE_H * 2;

    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN].x = SPRITE_CLIPS[196].x;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN].y = SPRITE_CLIPS[196].y;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN].w = TILE_W * 2;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN].h = TILE_H * 2;

    PACMAN_CLIPS_LEFT[PACMAN_LEFT_OPEN].x = SPRITE_CLIPS[192].x;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_OPEN].y = SPRITE_CLIPS[192].y;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_OPEN].w = TILE_W * 2;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_OPEN].h = TILE_H * 2;

    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN2].x = SPRITE_CLIPS[196].x;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN2].y = SPRITE_CLIPS[196].y;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN2].w = TILE_W * 2;
    PACMAN_CLIPS_LEFT[PACMAN_LEFT_HALFOPEN2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PACMAN_CLIPS_UP[PACMAN_UP_FULL].x = SPRITE_CLIPS[448].x;
    PACMAN_CLIPS_UP[PACMAN_UP_FULL].y = SPRITE_CLIPS[448].y;
    PACMAN_CLIPS_UP[PACMAN_UP_FULL].w = TILE_W * 2;
    PACMAN_CLIPS_UP[PACMAN_UP_FULL].h = TILE_H * 2;

    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN].x = SPRITE_CLIPS[198].x;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN].y = SPRITE_CLIPS[198].y;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN].w = TILE_W * 2;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN].h = TILE_H * 2;

    PACMAN_CLIPS_UP[PACMAN_UP_OPEN].x = SPRITE_CLIPS[194].x;
    PACMAN_CLIPS_UP[PACMAN_UP_OPEN].y = SPRITE_CLIPS[194].y;
    PACMAN_CLIPS_UP[PACMAN_UP_OPEN].w = TILE_W * 2;
    PACMAN_CLIPS_UP[PACMAN_UP_OPEN].h = TILE_H * 2;

    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN2].x = SPRITE_CLIPS[198].x;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN2].y = SPRITE_CLIPS[198].y;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN2].w = TILE_W * 2;
    PACMAN_CLIPS_UP[PACMAN_UP_HALFOPEN2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PACMAN_CLIPS_DOWN[PACMAN_DOWN_FULL].x = SPRITE_CLIPS[448].x;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_FULL].y = SPRITE_CLIPS[448].y;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_FULL].w = TILE_W * 2;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_FULL].h = TILE_H * 2;

    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN].x = SPRITE_CLIPS[206].x;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN].y = SPRITE_CLIPS[206].y;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN].w = TILE_W * 2;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN].h = TILE_H * 2;

    PACMAN_CLIPS_DOWN[PACMAN_DOWN_OPEN].x = SPRITE_CLIPS[202].x;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_OPEN].y = SPRITE_CLIPS[202].y;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_OPEN].w = TILE_W * 2;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_OPEN].h = TILE_H * 2;

    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN2].x = SPRITE_CLIPS[206].x;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN2].y = SPRITE_CLIPS[206].y;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN2].w = TILE_W * 2;
    PACMAN_CLIPS_DOWN[PACMAN_DOWN_HALFOPEN2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_1].x = SPRITE_CLIPS[456].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_1].y = SPRITE_CLIPS[456].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_1].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_1].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_2].x = SPRITE_CLIPS[458].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_2].y = SPRITE_CLIPS[458].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_2].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_2].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_3].x = SPRITE_CLIPS[460].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_3].y = SPRITE_CLIPS[460].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_3].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_3].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_4].x = SPRITE_CLIPS[462].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_4].y = SPRITE_CLIPS[462].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_4].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_4].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_5].x = SPRITE_CLIPS[464].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_5].y = SPRITE_CLIPS[464].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_5].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_5].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_6].x = SPRITE_CLIPS[466].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_6].y = SPRITE_CLIPS[466].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_6].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_6].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_7].x = SPRITE_CLIPS[468].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_7].y = SPRITE_CLIPS[468].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_7].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_7].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_8].x = SPRITE_CLIPS[470].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_8].y = SPRITE_CLIPS[470].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_8].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_8].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_9].x = SPRITE_CLIPS[472].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_9].y = SPRITE_CLIPS[472].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_9].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_9].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_10].x = SPRITE_CLIPS[474].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_10].y = SPRITE_CLIPS[474].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_10].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_10].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_11].x = SPRITE_CLIPS[476].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_11].y = SPRITE_CLIPS[476].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_11].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_11].h = TILE_H * 2;

    PACMAN_CLIPS_DEATH[PACMAN_DEATH_12].x = SPRITE_CLIPS[478].x;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_12].y = SPRITE_CLIPS[478].y;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_12].w = TILE_W * 2;
    PACMAN_CLIPS_DEATH[PACMAN_DEATH_12].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    ENERGIZER_CLIPS[PELLET_1].x = SPRITE_CLIPS[16].x;
    ENERGIZER_CLIPS[PELLET_1].y = SPRITE_CLIPS[16].y;
    ENERGIZER_CLIPS[PELLET_1].w = TILE_W;
    ENERGIZER_CLIPS[PELLET_1].h = TILE_H;

    ENERGIZER_CLIPS[PELLET_2].x = SPRITE_CLIPS[17].x;
    ENERGIZER_CLIPS[PELLET_2].y = SPRITE_CLIPS[17].y;
    ENERGIZER_CLIPS[PELLET_2].w = TILE_W;
    ENERGIZER_CLIPS[PELLET_2].h = TILE_H;

    //---------------------------------------------------------------------------------

    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_1].x = SPRITE_CLIPS[384].x;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_1].y = SPRITE_CLIPS[384].y;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_1].w = TILE_W * 2;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_1].h = TILE_H * 2;

    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_2].x = SPRITE_CLIPS[386].x;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_2].y = SPRITE_CLIPS[386].y;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_2].w = TILE_W * 2;
    BLINKY_CLIPS_RIGHT[BLINKY_RIGHT_2].h = TILE_H * 2;



    BLINKY_CLIPS_DOWN[BLINKY_DOWN_1].x = SPRITE_CLIPS[388].x;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_1].y = SPRITE_CLIPS[388].y;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_1].w = TILE_W * 2;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_1].h = TILE_H * 2;

    BLINKY_CLIPS_DOWN[BLINKY_DOWN_2].x = SPRITE_CLIPS[390].x;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_2].y = SPRITE_CLIPS[390].y;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_2].w = TILE_W * 2;
    BLINKY_CLIPS_DOWN[BLINKY_DOWN_2].h = TILE_H * 2;



    BLINKY_CLIPS_LEFT[BLINKY_LEFT_1].x = SPRITE_CLIPS[392].x;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_1].y = SPRITE_CLIPS[392].y;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_1].w = TILE_W * 2;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_1].h = TILE_H * 2;

    BLINKY_CLIPS_LEFT[BLINKY_LEFT_2].x = SPRITE_CLIPS[394].x;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_2].y = SPRITE_CLIPS[394].y;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_2].w = TILE_W * 2;
    BLINKY_CLIPS_LEFT[BLINKY_LEFT_2].h = TILE_H * 2;



    BLINKY_CLIPS_UP[BLINKY_UP_1].x = SPRITE_CLIPS[396].x;
    BLINKY_CLIPS_UP[BLINKY_UP_1].y = SPRITE_CLIPS[396].y;
    BLINKY_CLIPS_UP[BLINKY_UP_1].w = TILE_W * 2;
    BLINKY_CLIPS_UP[BLINKY_UP_1].h = TILE_H * 2;

    BLINKY_CLIPS_UP[BLINKY_UP_2].x = SPRITE_CLIPS[398].x;
    BLINKY_CLIPS_UP[BLINKY_UP_2].y = SPRITE_CLIPS[398].y;
    BLINKY_CLIPS_UP[BLINKY_UP_2].w = TILE_W * 2;
    BLINKY_CLIPS_UP[BLINKY_UP_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PINKY_CLIPS_RIGHT[PINKY_RIGHT_1].x = SPRITE_CLIPS[512].x;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_1].y = SPRITE_CLIPS[512].y;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_1].w = TILE_W * 2;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_1].h = TILE_H * 2;

    PINKY_CLIPS_RIGHT[PINKY_RIGHT_2].x = SPRITE_CLIPS[514].x;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_2].y = SPRITE_CLIPS[514].y;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_2].w = TILE_W * 2;
    PINKY_CLIPS_RIGHT[PINKY_RIGHT_2].h = TILE_H * 2;


    PINKY_CLIPS_LEFT[PINKY_LEFT_1].x = SPRITE_CLIPS[520].x;
    PINKY_CLIPS_LEFT[PINKY_LEFT_1].y = SPRITE_CLIPS[520].y;
    PINKY_CLIPS_LEFT[PINKY_LEFT_1].w = TILE_W * 2;
    PINKY_CLIPS_LEFT[PINKY_LEFT_1].h = TILE_H * 2;

    PINKY_CLIPS_LEFT[PINKY_LEFT_2].x = SPRITE_CLIPS[522].x;
    PINKY_CLIPS_LEFT[PINKY_LEFT_2].y = SPRITE_CLIPS[522].y;
    PINKY_CLIPS_LEFT[PINKY_LEFT_2].w = TILE_W * 2;
    PINKY_CLIPS_LEFT[PINKY_LEFT_2].h = TILE_H * 2;


    PINKY_CLIPS_UP[PINKY_UP_1].x = SPRITE_CLIPS[524].x;
    PINKY_CLIPS_UP[PINKY_UP_1].y = SPRITE_CLIPS[524].y;
    PINKY_CLIPS_UP[PINKY_UP_1].w = TILE_W * 2;
    PINKY_CLIPS_UP[PINKY_UP_1].h = TILE_H * 2;

    PINKY_CLIPS_UP[PINKY_UP_2].x = SPRITE_CLIPS[526].x;
    PINKY_CLIPS_UP[PINKY_UP_2].y = SPRITE_CLIPS[526].y;
    PINKY_CLIPS_UP[PINKY_UP_2].w = TILE_W * 2;
    PINKY_CLIPS_UP[PINKY_UP_2].h = TILE_H * 2;


    PINKY_CLIPS_DOWN[PINKY_DOWN_1].x = SPRITE_CLIPS[516].x;
    PINKY_CLIPS_DOWN[PINKY_DOWN_1].y = SPRITE_CLIPS[516].y;
    PINKY_CLIPS_DOWN[PINKY_DOWN_1].w = TILE_W * 2;
    PINKY_CLIPS_DOWN[PINKY_DOWN_1].h = TILE_H * 2;

    PINKY_CLIPS_DOWN[PINKY_DOWN_2].x = SPRITE_CLIPS[518].x;
    PINKY_CLIPS_DOWN[PINKY_DOWN_2].y = SPRITE_CLIPS[518].y;
    PINKY_CLIPS_DOWN[PINKY_DOWN_2].w = TILE_W * 2;
    PINKY_CLIPS_DOWN[PINKY_DOWN_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    INKY_CLIPS_RIGHT[INKY_RIGHT_1].x = SPRITE_CLIPS[528].x;
    INKY_CLIPS_RIGHT[INKY_RIGHT_1].y = SPRITE_CLIPS[528].y;
    INKY_CLIPS_RIGHT[INKY_RIGHT_1].w = TILE_W * 2;
    INKY_CLIPS_RIGHT[INKY_RIGHT_1].h = TILE_H * 2;

    INKY_CLIPS_RIGHT[INKY_RIGHT_2].x = SPRITE_CLIPS[530].x;
    INKY_CLIPS_RIGHT[INKY_RIGHT_2].y = SPRITE_CLIPS[530].y;
    INKY_CLIPS_RIGHT[INKY_RIGHT_2].w = TILE_W * 2;
    INKY_CLIPS_RIGHT[INKY_RIGHT_2].h = TILE_H * 2;


    INKY_CLIPS_LEFT[INKY_LEFT_1].x = SPRITE_CLIPS[536].x;
    INKY_CLIPS_LEFT[INKY_LEFT_1].y = SPRITE_CLIPS[536].y;
    INKY_CLIPS_LEFT[INKY_LEFT_1].w = TILE_W * 2;
    INKY_CLIPS_LEFT[INKY_LEFT_1].h = TILE_H * 2;

    INKY_CLIPS_LEFT[INKY_LEFT_2].x = SPRITE_CLIPS[538].x;
    INKY_CLIPS_LEFT[INKY_LEFT_2].y = SPRITE_CLIPS[538].y;
    INKY_CLIPS_LEFT[INKY_LEFT_2].w = TILE_W * 2;
    INKY_CLIPS_LEFT[INKY_LEFT_2].h = TILE_H * 2;


    INKY_CLIPS_UP[INKY_UP_1].x = SPRITE_CLIPS[540].x;
    INKY_CLIPS_UP[INKY_UP_1].y = SPRITE_CLIPS[540].y;
    INKY_CLIPS_UP[INKY_UP_1].w = TILE_W * 2;
    INKY_CLIPS_UP[INKY_UP_1].h = TILE_H * 2;

    INKY_CLIPS_UP[INKY_UP_2].x = SPRITE_CLIPS[542].x;
    INKY_CLIPS_UP[INKY_UP_2].y = SPRITE_CLIPS[542].y;
    INKY_CLIPS_UP[INKY_UP_2].w = TILE_W * 2;
    INKY_CLIPS_UP[INKY_UP_2].h = TILE_H * 2;


    INKY_CLIPS_DOWN[INKY_DOWN_1].x = SPRITE_CLIPS[532].x;
    INKY_CLIPS_DOWN[INKY_DOWN_1].y = SPRITE_CLIPS[532].y;
    INKY_CLIPS_DOWN[INKY_DOWN_1].w = TILE_W * 2;
    INKY_CLIPS_DOWN[INKY_DOWN_1].h = TILE_H * 2;

    INKY_CLIPS_DOWN[INKY_DOWN_2].x = SPRITE_CLIPS[534].x;
    INKY_CLIPS_DOWN[INKY_DOWN_2].y = SPRITE_CLIPS[534].y;
    INKY_CLIPS_DOWN[INKY_DOWN_2].w = TILE_W * 2;
    INKY_CLIPS_DOWN[INKY_DOWN_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_1].x = SPRITE_CLIPS[576].x;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_1].y = SPRITE_CLIPS[576].y;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_1].w = TILE_W * 2;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_1].h = TILE_H * 2;

    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_2].x = SPRITE_CLIPS[578].x;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_2].y = SPRITE_CLIPS[578].y;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_2].w = TILE_W * 2;
    CLYDE_CLIPS_RIGHT[CLYDE_RIGHT_2].h = TILE_H * 2;


    CLYDE_CLIPS_LEFT[CLYDE_LEFT_1].x = SPRITE_CLIPS[584].x;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_1].y = SPRITE_CLIPS[584].y;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_1].w = TILE_W * 2;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_1].h = TILE_H * 2;

    CLYDE_CLIPS_LEFT[CLYDE_LEFT_2].x = SPRITE_CLIPS[586].x;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_2].y = SPRITE_CLIPS[586].y;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_2].w = TILE_W * 2;
    CLYDE_CLIPS_LEFT[CLYDE_LEFT_2].h = TILE_H * 2;


    CLYDE_CLIPS_UP[CLYDE_UP_1].x = SPRITE_CLIPS[588].x;
    CLYDE_CLIPS_UP[CLYDE_UP_1].y = SPRITE_CLIPS[588].y;
    CLYDE_CLIPS_UP[CLYDE_UP_1].w = TILE_W * 2;
    CLYDE_CLIPS_UP[CLYDE_UP_1].h = TILE_H * 2;

    CLYDE_CLIPS_UP[CLYDE_UP_2].x = SPRITE_CLIPS[590].x;
    CLYDE_CLIPS_UP[CLYDE_UP_2].y = SPRITE_CLIPS[590].y;
    CLYDE_CLIPS_UP[CLYDE_UP_2].w = TILE_W * 2;
    CLYDE_CLIPS_UP[CLYDE_UP_2].h = TILE_H * 2;


    CLYDE_CLIPS_DOWN[CLYDE_DOWN_1].x = SPRITE_CLIPS[580].x;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_1].y = SPRITE_CLIPS[580].y;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_1].w = TILE_W * 2;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_1].h = TILE_H * 2;

    CLYDE_CLIPS_DOWN[CLYDE_DOWN_2].x = SPRITE_CLIPS[582].x;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_2].y = SPRITE_CLIPS[582].y;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_2].w = TILE_W * 2;
    CLYDE_CLIPS_DOWN[CLYDE_DOWN_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    EYES_CLIPS_RIGHT[EYES_RIGHT_1].x = SPRITE_CLIPS[592].x;
    EYES_CLIPS_RIGHT[EYES_RIGHT_1].y = SPRITE_CLIPS[592].y;
    EYES_CLIPS_RIGHT[EYES_RIGHT_1].w = TILE_W * 2;
    EYES_CLIPS_RIGHT[EYES_RIGHT_1].h = TILE_H * 2;

    EYES_CLIPS_RIGHT[EYES_RIGHT_2].x = SPRITE_CLIPS[594].x;
    EYES_CLIPS_RIGHT[EYES_RIGHT_2].y = SPRITE_CLIPS[594].y;
    EYES_CLIPS_RIGHT[EYES_RIGHT_2].w = TILE_W * 2;
    EYES_CLIPS_RIGHT[EYES_RIGHT_2].h = TILE_H * 2;


    EYES_CLIPS_LEFT[EYES_LEFT_1].x = SPRITE_CLIPS[600].x;
    EYES_CLIPS_LEFT[EYES_LEFT_1].y = SPRITE_CLIPS[600].y;
    EYES_CLIPS_LEFT[EYES_LEFT_1].w = TILE_W * 2;
    EYES_CLIPS_LEFT[EYES_LEFT_1].h = TILE_H * 2;

    EYES_CLIPS_LEFT[EYES_LEFT_2].x = SPRITE_CLIPS[602].x;
    EYES_CLIPS_LEFT[EYES_LEFT_2].y = SPRITE_CLIPS[602].y;
    EYES_CLIPS_LEFT[EYES_LEFT_2].w = TILE_W * 2;
    EYES_CLIPS_LEFT[EYES_LEFT_2].h = TILE_H * 2;


    EYES_CLIPS_UP[EYES_UP_1].x = SPRITE_CLIPS[604].x;
    EYES_CLIPS_UP[EYES_UP_1].y = SPRITE_CLIPS[604].y;
    EYES_CLIPS_UP[EYES_UP_1].w = TILE_W * 2;
    EYES_CLIPS_UP[EYES_UP_1].h = TILE_H * 2;

    EYES_CLIPS_UP[EYES_UP_2].x = SPRITE_CLIPS[606].x;
    EYES_CLIPS_UP[EYES_UP_2].y = SPRITE_CLIPS[606].y;
    EYES_CLIPS_UP[EYES_UP_2].w = TILE_W * 2;
    EYES_CLIPS_UP[EYES_UP_2].h = TILE_H * 2;


    EYES_CLIPS_DOWN[EYES_DOWN_1].x = SPRITE_CLIPS[596].x;
    EYES_CLIPS_DOWN[EYES_DOWN_1].y = SPRITE_CLIPS[596].y;
    EYES_CLIPS_DOWN[EYES_DOWN_1].w = TILE_W * 2;
    EYES_CLIPS_DOWN[EYES_DOWN_1].h = TILE_H * 2;

    EYES_CLIPS_DOWN[EYES_DOWN_2].x = SPRITE_CLIPS[598].x;
    EYES_CLIPS_DOWN[EYES_DOWN_2].y = SPRITE_CLIPS[598].y;
    EYES_CLIPS_DOWN[EYES_DOWN_2].w = TILE_W * 2;
    EYES_CLIPS_DOWN[EYES_DOWN_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    FRIGHT_CLIPS[FRIGHT_1].x = SPRITE_CLIPS[272].x;
    FRIGHT_CLIPS[FRIGHT_1].y = SPRITE_CLIPS[272].y;
    FRIGHT_CLIPS[FRIGHT_1].w = TILE_W * 2;
    FRIGHT_CLIPS[FRIGHT_1].h = TILE_H * 2;

    FRIGHT_CLIPS[FRIGHT_2].x = SPRITE_CLIPS[274].x;
    FRIGHT_CLIPS[FRIGHT_2].y = SPRITE_CLIPS[274].y;
    FRIGHT_CLIPS[FRIGHT_2].w = TILE_W * 2;
    FRIGHT_CLIPS[FRIGHT_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    FRIGHT_END_CLIPS[FRIGHT_END_1].x = SPRITE_CLIPS[268].x;
    FRIGHT_END_CLIPS[FRIGHT_END_1].y = SPRITE_CLIPS[268].y;
    FRIGHT_END_CLIPS[FRIGHT_END_1].w = TILE_W * 2;
    FRIGHT_END_CLIPS[FRIGHT_END_1].h = TILE_H * 2;

    FRIGHT_END_CLIPS[FRIGHT_END_2].x = SPRITE_CLIPS[270].x;
    FRIGHT_END_CLIPS[FRIGHT_END_2].y = SPRITE_CLIPS[270].y;
    FRIGHT_END_CLIPS[FRIGHT_END_2].w = TILE_W * 2;
    FRIGHT_END_CLIPS[FRIGHT_END_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    LETTER_CLIPS[LETTER_A].x = SPRITE_CLIPS[65].x;
    LETTER_CLIPS[LETTER_A].y = SPRITE_CLIPS[65].y;
    LETTER_CLIPS[LETTER_A].w = TILE_W;
    LETTER_CLIPS[LETTER_A].h = TILE_H;

    LETTER_CLIPS[LETTER_C].x = SPRITE_CLIPS[67].x;
    LETTER_CLIPS[LETTER_C].y = SPRITE_CLIPS[67].y;
    LETTER_CLIPS[LETTER_C].w = TILE_W;
    LETTER_CLIPS[LETTER_C].h = TILE_H;

    LETTER_CLIPS[LETTER_D].x = SPRITE_CLIPS[68].x;
    LETTER_CLIPS[LETTER_D].y = SPRITE_CLIPS[68].y;
    LETTER_CLIPS[LETTER_D].w = TILE_W;
    LETTER_CLIPS[LETTER_D].h = TILE_H;

    LETTER_CLIPS[LETTER_I].x = SPRITE_CLIPS[73].x;
    LETTER_CLIPS[LETTER_I].y = SPRITE_CLIPS[73].y;
    LETTER_CLIPS[LETTER_I].w = TILE_W;
    LETTER_CLIPS[LETTER_I].h = TILE_H;

    LETTER_CLIPS[LETTER_E].x = SPRITE_CLIPS[69].x;
    LETTER_CLIPS[LETTER_E].y = SPRITE_CLIPS[69].y;
    LETTER_CLIPS[LETTER_E].w = TILE_W;
    LETTER_CLIPS[LETTER_E].h = TILE_H;

    LETTER_CLIPS[LETTER_G].x = SPRITE_CLIPS[71].x;
    LETTER_CLIPS[LETTER_G].y = SPRITE_CLIPS[71].y;
    LETTER_CLIPS[LETTER_G].w = TILE_W;
    LETTER_CLIPS[LETTER_G].h = TILE_H;

    LETTER_CLIPS[LETTER_H].x = SPRITE_CLIPS[72].x;
    LETTER_CLIPS[LETTER_H].y = SPRITE_CLIPS[72].y;
    LETTER_CLIPS[LETTER_H].w = TILE_W;
    LETTER_CLIPS[LETTER_H].h = TILE_H;

    LETTER_CLIPS[LETTER_O].x = SPRITE_CLIPS[79].x;
    LETTER_CLIPS[LETTER_O].y = SPRITE_CLIPS[79].y;
    LETTER_CLIPS[LETTER_O].w = TILE_W;
    LETTER_CLIPS[LETTER_O].h = TILE_H;

    LETTER_CLIPS[LETTER_R].x = SPRITE_CLIPS[82].x;
    LETTER_CLIPS[LETTER_R].y = SPRITE_CLIPS[82].y;
    LETTER_CLIPS[LETTER_R].w = TILE_W;
    LETTER_CLIPS[LETTER_R].h = TILE_H;

    LETTER_CLIPS[LETTER_S].x = SPRITE_CLIPS[83].x;
    LETTER_CLIPS[LETTER_S].y = SPRITE_CLIPS[83].y;
    LETTER_CLIPS[LETTER_S].w = TILE_W;
    LETTER_CLIPS[LETTER_S].h = TILE_H;

    LETTER_CLIPS[LETTER_Y].x = SPRITE_CLIPS[89].x;
    LETTER_CLIPS[LETTER_Y].y = SPRITE_CLIPS[89].y;
    LETTER_CLIPS[LETTER_Y].w = TILE_W;
    LETTER_CLIPS[LETTER_Y].h = TILE_H;

    LETTER_CLIPS[LETTER_U].x = SPRITE_CLIPS[85].x;
    LETTER_CLIPS[LETTER_U].y = SPRITE_CLIPS[85].y;
    LETTER_CLIPS[LETTER_U].w = TILE_W;
    LETTER_CLIPS[LETTER_U].h = TILE_H;

    LETTER_CLIPS[LETTER_P].x = SPRITE_CLIPS[80].x;
    LETTER_CLIPS[LETTER_P].y = SPRITE_CLIPS[80].y;
    LETTER_CLIPS[LETTER_P].w = TILE_W;
    LETTER_CLIPS[LETTER_P].h = TILE_H;

    LETTER_CLIPS[LETTER_EX].x = SPRITE_CLIPS[91].x;
    LETTER_CLIPS[LETTER_EX].y = SPRITE_CLIPS[91].y;
    LETTER_CLIPS[LETTER_EX].w = TILE_W;
    LETTER_CLIPS[LETTER_EX].h = TILE_H;

    LETTER_CLIPS[LETTER_M].x = SPRITE_CLIPS[77].x;
    LETTER_CLIPS[LETTER_M].y = SPRITE_CLIPS[77].y;
    LETTER_CLIPS[LETTER_M].w = TILE_W;
    LETTER_CLIPS[LETTER_M].h = TILE_H;

    LETTER_CLIPS[LETTER_V].x = SPRITE_CLIPS[86].x;
    LETTER_CLIPS[LETTER_V].y = SPRITE_CLIPS[86].y;
    LETTER_CLIPS[LETTER_V].w = TILE_W;
    LETTER_CLIPS[LETTER_V].h = TILE_H;

    LETTER_CLIPS[LETTER_R1].x = SPRITE_CLIPS[10].x;
    LETTER_CLIPS[LETTER_R1].y = SPRITE_CLIPS[10].y;
    LETTER_CLIPS[LETTER_R1].w = TILE_W;
    LETTER_CLIPS[LETTER_R1].h = TILE_H;

    LETTER_CLIPS[LETTER_E1].x = SPRITE_CLIPS[11].x;
    LETTER_CLIPS[LETTER_E1].y = SPRITE_CLIPS[11].y;
    LETTER_CLIPS[LETTER_E1].w = TILE_W;
    LETTER_CLIPS[LETTER_E1].h = TILE_H;

    LETTER_CLIPS[LETTER_G2].x = SPRITE_CLIPS[0].x;
    LETTER_CLIPS[LETTER_G2].y = SPRITE_CLIPS[0].y;
    LETTER_CLIPS[LETTER_G2].w = TILE_W;
    LETTER_CLIPS[LETTER_G2].h = TILE_H;

    LETTER_CLIPS[LETTER_A2].x = SPRITE_CLIPS[1].x;
    LETTER_CLIPS[LETTER_A2].y = SPRITE_CLIPS[1].y;
    LETTER_CLIPS[LETTER_A2].w = TILE_W;
    LETTER_CLIPS[LETTER_A2].h = TILE_H;

    LETTER_CLIPS[LETTER_M2].x = SPRITE_CLIPS[2].x;
    LETTER_CLIPS[LETTER_M2].y = SPRITE_CLIPS[2].y;
    LETTER_CLIPS[LETTER_M2].w = TILE_W;
    LETTER_CLIPS[LETTER_M2].h = TILE_H;

    LETTER_CLIPS[LETTER_E2].x = SPRITE_CLIPS[3].x;
    LETTER_CLIPS[LETTER_E2].y = SPRITE_CLIPS[3].y;
    LETTER_CLIPS[LETTER_E2].w = TILE_W;
    LETTER_CLIPS[LETTER_E2].h = TILE_H;

    LETTER_CLIPS[LETTER_O2].x = SPRITE_CLIPS[4].x;
    LETTER_CLIPS[LETTER_O2].y = SPRITE_CLIPS[4].y;
    LETTER_CLIPS[LETTER_O2].w = TILE_W;
    LETTER_CLIPS[LETTER_O2].h = TILE_H;

    LETTER_CLIPS[LETTER_V2].x = SPRITE_CLIPS[5].x;
    LETTER_CLIPS[LETTER_V2].y = SPRITE_CLIPS[5].y;
    LETTER_CLIPS[LETTER_V2].w = TILE_W;
    LETTER_CLIPS[LETTER_V2].h = TILE_H;

    LETTER_CLIPS[LETTER_R2].x = SPRITE_CLIPS[7].x;
    LETTER_CLIPS[LETTER_R2].y = SPRITE_CLIPS[7].y;
    LETTER_CLIPS[LETTER_R2].w = TILE_W;
    LETTER_CLIPS[LETTER_R2].h = TILE_H;

    //---------------------------------------------------------------------------------

    DIGIT_CLIPS[DIGIT_0].x = SPRITE_CLIPS[48].x;
    DIGIT_CLIPS[DIGIT_0].y = SPRITE_CLIPS[48].y;
    DIGIT_CLIPS[DIGIT_0].w = TILE_W;
    DIGIT_CLIPS[DIGIT_0].h = TILE_H;

    DIGIT_CLIPS[DIGIT_1].x = SPRITE_CLIPS[49].x;
    DIGIT_CLIPS[DIGIT_1].y = SPRITE_CLIPS[49].y;
    DIGIT_CLIPS[DIGIT_1].w = TILE_W;
    DIGIT_CLIPS[DIGIT_1].h = TILE_H;

    DIGIT_CLIPS[DIGIT_2].x = SPRITE_CLIPS[50].x;
    DIGIT_CLIPS[DIGIT_2].y = SPRITE_CLIPS[50].y;
    DIGIT_CLIPS[DIGIT_2].w = TILE_W;
    DIGIT_CLIPS[DIGIT_2].h = TILE_H;

    DIGIT_CLIPS[DIGIT_3].x = SPRITE_CLIPS[51].x;
    DIGIT_CLIPS[DIGIT_3].y = SPRITE_CLIPS[51].y;
    DIGIT_CLIPS[DIGIT_3].w = TILE_W;
    DIGIT_CLIPS[DIGIT_3].h = TILE_H;

    DIGIT_CLIPS[DIGIT_4].x = SPRITE_CLIPS[52].x;
    DIGIT_CLIPS[DIGIT_4].y = SPRITE_CLIPS[52].y;
    DIGIT_CLIPS[DIGIT_4].w = TILE_W;
    DIGIT_CLIPS[DIGIT_4].h = TILE_H;

    DIGIT_CLIPS[DIGIT_5].x = SPRITE_CLIPS[53].x;
    DIGIT_CLIPS[DIGIT_5].y = SPRITE_CLIPS[53].y;
    DIGIT_CLIPS[DIGIT_5].w = TILE_W;
    DIGIT_CLIPS[DIGIT_5].h = TILE_H;

    DIGIT_CLIPS[DIGIT_6].x = SPRITE_CLIPS[54].x;
    DIGIT_CLIPS[DIGIT_6].y = SPRITE_CLIPS[54].y;
    DIGIT_CLIPS[DIGIT_6].w = TILE_W;
    DIGIT_CLIPS[DIGIT_6].h = TILE_H;

    DIGIT_CLIPS[DIGIT_7].x = SPRITE_CLIPS[55].x;
    DIGIT_CLIPS[DIGIT_7].y = SPRITE_CLIPS[55].y;
    DIGIT_CLIPS[DIGIT_7].w = TILE_W;
    DIGIT_CLIPS[DIGIT_7].h = TILE_H;

    DIGIT_CLIPS[DIGIT_8].x = SPRITE_CLIPS[56].x;
    DIGIT_CLIPS[DIGIT_8].y = SPRITE_CLIPS[56].y;
    DIGIT_CLIPS[DIGIT_8].w = TILE_W;
    DIGIT_CLIPS[DIGIT_8].h = TILE_H;

    DIGIT_CLIPS[DIGIT_9].x = SPRITE_CLIPS[57].x;
    DIGIT_CLIPS[DIGIT_9].y = SPRITE_CLIPS[57].y;
    DIGIT_CLIPS[DIGIT_9].w = TILE_W;
    DIGIT_CLIPS[DIGIT_9].h = TILE_H;

    //---------------------------------------------------------------------------------

    SCORE_CLIPS[SCORE_200].x = SPRITE_CLIPS[400].x;
    SCORE_CLIPS[SCORE_200].y = SPRITE_CLIPS[400].y;
    SCORE_CLIPS[SCORE_200].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_200].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_400].x = SPRITE_CLIPS[402].x;
    SCORE_CLIPS[SCORE_400].y = SPRITE_CLIPS[402].y;
    SCORE_CLIPS[SCORE_400].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_400].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_800].x = SPRITE_CLIPS[404].x;
    SCORE_CLIPS[SCORE_800].y = SPRITE_CLIPS[404].y;
    SCORE_CLIPS[SCORE_800].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_800].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_1600].x = SPRITE_CLIPS[406].x;
    SCORE_CLIPS[SCORE_1600].y = SPRITE_CLIPS[406].y;
    SCORE_CLIPS[SCORE_1600].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_1600].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_100].x = SPRITE_CLIPS[128].x;
    SCORE_CLIPS[SCORE_100].y = SPRITE_CLIPS[128].y;
    SCORE_CLIPS[SCORE_100].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_100].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_300].x = SPRITE_CLIPS[130].x;
    SCORE_CLIPS[SCORE_300].y = SPRITE_CLIPS[130].y;
    SCORE_CLIPS[SCORE_300].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_300].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_500].x = SPRITE_CLIPS[132].x;
    SCORE_CLIPS[SCORE_500].y = SPRITE_CLIPS[132].y;
    SCORE_CLIPS[SCORE_500].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_500].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_700].x = SPRITE_CLIPS[134].x;
    SCORE_CLIPS[SCORE_700].y = SPRITE_CLIPS[134].y;
    SCORE_CLIPS[SCORE_700].w = TILE_W * 2;
    SCORE_CLIPS[SCORE_700].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_1000].x = SPRITE_CLIPS[136].x;
    SCORE_CLIPS[SCORE_1000].y = SPRITE_CLIPS[136].y;
    SCORE_CLIPS[SCORE_1000].w = TILE_W * 4;
    SCORE_CLIPS[SCORE_1000].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_2000].x = SPRITE_CLIPS[140].x;
    SCORE_CLIPS[SCORE_2000].y = SPRITE_CLIPS[140].y;
    SCORE_CLIPS[SCORE_2000].w = TILE_W * 4;
    SCORE_CLIPS[SCORE_2000].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_3000].x = SPRITE_CLIPS[144].x;
    SCORE_CLIPS[SCORE_3000].y = SPRITE_CLIPS[144].y;
    SCORE_CLIPS[SCORE_3000].w = TILE_W * 4;
    SCORE_CLIPS[SCORE_3000].h = TILE_H * 2;

    SCORE_CLIPS[SCORE_5000].x = SPRITE_CLIPS[148].x;
    SCORE_CLIPS[SCORE_5000].y = SPRITE_CLIPS[148].y;
    SCORE_CLIPS[SCORE_5000].w = TILE_W * 4;
    SCORE_CLIPS[SCORE_5000].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    FRUIT_CLIPS[CHERRY].x = SPRITE_CLIPS[320].x;
    FRUIT_CLIPS[CHERRY].y = SPRITE_CLIPS[320].y;
    FRUIT_CLIPS[CHERRY].w = TILE_W * 2;
    FRUIT_CLIPS[CHERRY].h = TILE_H * 2;

    FRUIT_CLIPS[STRAWBERRY].x = SPRITE_CLIPS[322].x;
    FRUIT_CLIPS[STRAWBERRY].y = SPRITE_CLIPS[322].y;
    FRUIT_CLIPS[STRAWBERRY].w = TILE_W * 2;
    FRUIT_CLIPS[STRAWBERRY].h = TILE_H * 2;

    FRUIT_CLIPS[ORANGE].x = SPRITE_CLIPS[324].x;
    FRUIT_CLIPS[ORANGE].y = SPRITE_CLIPS[324].y;
    FRUIT_CLIPS[ORANGE].w = TILE_W * 2;
    FRUIT_CLIPS[ORANGE].h = TILE_H * 2;

    FRUIT_CLIPS[APPLE].x = SPRITE_CLIPS[326].x;
    FRUIT_CLIPS[APPLE].y = SPRITE_CLIPS[326].y;
    FRUIT_CLIPS[APPLE].w = TILE_W * 2;
    FRUIT_CLIPS[APPLE].h = TILE_H * 2;

    FRUIT_CLIPS[MELON].x = SPRITE_CLIPS[328].x;
    FRUIT_CLIPS[MELON].y = SPRITE_CLIPS[328].y;
    FRUIT_CLIPS[MELON].w = TILE_W * 2;
    FRUIT_CLIPS[MELON].h = TILE_H * 2;

    FRUIT_CLIPS[GALAXIAN_BOSS].x = SPRITE_CLIPS[330].x;
    FRUIT_CLIPS[GALAXIAN_BOSS].y = SPRITE_CLIPS[330].y;
    FRUIT_CLIPS[GALAXIAN_BOSS].w = TILE_W * 2;
    FRUIT_CLIPS[GALAXIAN_BOSS].h = TILE_H * 2;

    FRUIT_CLIPS[BELL].x = SPRITE_CLIPS[332].x;
    FRUIT_CLIPS[BELL].y = SPRITE_CLIPS[332].y;
    FRUIT_CLIPS[BELL].w = TILE_W * 2;
    FRUIT_CLIPS[BELL].h = TILE_H * 2;

    FRUIT_CLIPS[KEY].x = SPRITE_CLIPS[334].x;
    FRUIT_CLIPS[KEY].y = SPRITE_CLIPS[334].y;
    FRUIT_CLIPS[KEY].w = TILE_W * 2;
    FRUIT_CLIPS[KEY].h = TILE_H * 2;

    FRUIT_CLIPS[PACMAN_LIFE_ICON].x = SPRITE_CLIPS[408].x;
    FRUIT_CLIPS[PACMAN_LIFE_ICON].y = SPRITE_CLIPS[408].y;
    FRUIT_CLIPS[PACMAN_LIFE_ICON].w = TILE_W * 2;
    FRUIT_CLIPS[PACMAN_LIFE_ICON].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    BIG_PACMAN_CLIPS[PACMAN_RIGHT_FULL].x = SPRITE_CLIPS[220].x;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_FULL].y = SPRITE_CLIPS[220].y;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_FULL].w = TILE_W * 4;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_FULL].h = TILE_H * 4;

    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN].x = SPRITE_CLIPS[216].x;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN].y = SPRITE_CLIPS[216].y;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN].w = TILE_W * 4;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN].h = TILE_H * 4;

    BIG_PACMAN_CLIPS[PACMAN_RIGHT_OPEN].x = SPRITE_CLIPS[212].x;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_OPEN].y = SPRITE_CLIPS[212].y;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_OPEN].w = TILE_W * 4;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_OPEN].h = TILE_H * 4;

    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN2].x = SPRITE_CLIPS[216].x;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN2].y = SPRITE_CLIPS[216].y;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN2].w = TILE_W * 4;
    BIG_PACMAN_CLIPS[PACMAN_RIGHT_HALFOPEN2].h = TILE_H * 4;

    //---------------------------------------------------------------------------------

    TORN_BLINKY_CLIPS[TORN_EYES_UP].x = SPRITE_CLIPS[452].x;
    TORN_BLINKY_CLIPS[TORN_EYES_UP].y = SPRITE_CLIPS[452].y;
    TORN_BLINKY_CLIPS[TORN_EYES_UP].w = TILE_W * 2;
    TORN_BLINKY_CLIPS[TORN_EYES_UP].h = TILE_H * 2;

    TORN_BLINKY_CLIPS[TORN_EYES_DOWN].x = SPRITE_CLIPS[454].x;
    TORN_BLINKY_CLIPS[TORN_EYES_DOWN].y = SPRITE_CLIPS[454].y;
    TORN_BLINKY_CLIPS[TORN_EYES_DOWN].w = TILE_W * 2;
    TORN_BLINKY_CLIPS[TORN_EYES_DOWN].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_1].x = SPRITE_CLIPS[336].x;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_1].y = SPRITE_CLIPS[336].y;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_1].w = TILE_W * 2;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_1].h = TILE_H * 2;

    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_2].x = SPRITE_CLIPS[338].x;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_2].y = SPRITE_CLIPS[338].y;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_2].w = TILE_W * 2;
    PATCHED_BLINKY_CLIPS[BLINKY_LEFT_2].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    BLINKY_CLOAK_TEAR_CLIPS[NAIL].x = SPRITE_CLIPS[350].x;
    BLINKY_CLOAK_TEAR_CLIPS[NAIL].y = SPRITE_CLIPS[350].y;
    BLINKY_CLOAK_TEAR_CLIPS[NAIL].w = TILE_W * 2;
    BLINKY_CLOAK_TEAR_CLIPS[NAIL].h = TILE_H * 2;

    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_1].x = SPRITE_CLIPS[410].x;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_1].y = SPRITE_CLIPS[410].y;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_1].w = TILE_W * 2;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_1].h = TILE_H * 2;

    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_2].x = SPRITE_CLIPS[412].x;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_2].y = SPRITE_CLIPS[412].y;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_2].w = TILE_W * 2;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_2].h = TILE_H * 2;

    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_3].x = SPRITE_CLIPS[414].x;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_3].y = SPRITE_CLIPS[414].y;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_3].w = TILE_W * 2;
    BLINKY_CLOAK_TEAR_CLIPS[STRETCH_3].h = TILE_H * 2;

    BLINKY_CLOAK_TEAR_CLIPS[TORN].x = SPRITE_CLIPS[348].x;
    BLINKY_CLOAK_TEAR_CLIPS[TORN].y = SPRITE_CLIPS[348].y;
    BLINKY_CLOAK_TEAR_CLIPS[TORN].w = TILE_W * 2;
    BLINKY_CLOAK_TEAR_CLIPS[TORN].h = TILE_H * 2;

    //---------------------------------------------------------------------------------

    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_1].x = SPRITE_CLIPS[340].x;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_1].y = SPRITE_CLIPS[340].y;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_1].w = TILE_W * 4;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_1].h = TILE_H * 2;

    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_2].x = SPRITE_CLIPS[344].x;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_2].y = SPRITE_CLIPS[344].y;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_2].w = TILE_W * 4;
    BLINKY_WITHOUT_CLOAK_CLIPS[WITHOUT_CLOAK_2].h = TILE_H * 2;

}